import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { getCurrency } from '@/lib/currencies'

const resend = new Resend(process.env.RESEND_API_KEY)

function getNextDate(date: string, frequency: string): string {
  const d = new Date(date)
  switch (frequency) {
    case 'weekly': d.setDate(d.getDate() + 7); break
    case 'monthly': d.setMonth(d.getMonth() + 1); break
    case 'quarterly': d.setMonth(d.getMonth() + 3); break
    case 'yearly': d.setFullYear(d.getFullYear() + 1); break
  }
  return d.toISOString().split('T')[0]
}

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabaseAdmin
    .from('profiles')
    .select('firm_id, full_name')
    .eq('id', user.id)
    .single()

  if (!profile) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const today = new Date().toISOString().split('T')[0]

  const { data: recurringInvoices } = await supabaseAdmin
    .from('recurring_invoices')
    .select('*, profiles!client_id(full_name)')
    .eq('firm_id', profile.firm_id)
    .eq('status', 'active')
    .lte('next_invoice_date', today)

  const { data: firm } = await supabaseAdmin
    .from('firms')
    .select('name, currency')
    .eq('id', profile.firm_id)
    .single()

  const cur = getCurrency(firm?.currency || 'GBP')

  let generated = 0

  for (const rec of recurringInvoices || []) {
    if (rec.end_date && rec.end_date < today) {
      await supabaseAdmin
        .from('recurring_invoices')
        .update({ status: 'cancelled' })
        .eq('id', rec.id)
      continue
    }

    const invoiceNumber = 'INV-' + new Date().getFullYear() + '-' + String(Math.floor(Math.random() * 900) + 100)

    const dueDate = getNextDate(today, rec.frequency)

    const { data: invoice } = await supabaseAdmin
      .from('invoices')
      .insert({
        firm_id: profile.firm_id,
        client_id: rec.client_id,
        invoice_number: invoiceNumber,
        amount: rec.amount,
        status: 'pending',
        issued_at: new Date().toISOString(),
        due_at: dueDate,
        description: rec.description || 'Recurring invoice',
        currency: firm?.currency || 'GBP',
      })
      .select()
      .single()

    const nextDate = getNextDate(rec.next_invoice_date, rec.frequency)
    await supabaseAdmin
      .from('recurring_invoices')
      .update({
        next_invoice_date: nextDate,
        invoice_count: (rec.invoice_count || 0) + 1
      })
      .eq('id', rec.id)

    // Create notification for admin
    await supabaseAdmin.from('notifications').insert({
      firm_id: profile.firm_id,
      user_id: user.id,
      type: 'invoice_paid',
      title: 'Recurring invoice generated',
      message: `${cur.symbol}${rec.amount.toLocaleString()} invoice generated for ${(rec.profiles as any)?.full_name || 'client'}`,
      action_url: '/dashboard/invoices',
      action_label: 'View invoices →',
      read: false,
    })

    // Send email
    const { data: clientAuth } = await supabaseAdmin.auth.admin.getUserById(rec.client_id)
    const clientEmail = clientAuth?.user?.email

    if (clientEmail) {
      const portalUrl = process.env.NEXT_PUBLIC_APP_URL + '/portal'
      try {
        await resend.emails.send({
          from: process.env.RESEND_FROM || 'hello@firmflow.uk',
          to: clientEmail,
          subject: 'New invoice from ' + (firm?.name || 'your firm') + ' — ' + invoiceNumber,
          html: `
            <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:600px;margin:0 auto;background:#ffffff">
              <div style="background:#1C64F2;padding:32px 40px;border-radius:12px 12px 0 0">
                <div style="font-size:22px;font-weight:800;color:#ffffff;letter-spacing:-0.04em">⬡ FirmFlow</div>
                <div style="color:rgba(255,255,255,0.8);font-size:14px;margin-top:4px">New invoice</div>
              </div>
              <div style="padding:40px;border:1px solid #E2E8F0;border-top:none;border-radius:0 0 12px 12px">
                <p style="font-size:16px;color:#0F172A;margin:0 0 8px">Hello <strong>${(rec.profiles as any)?.full_name || 'there'}</strong>,</p>
                <p style="font-size:14px;color:#475569;margin:0 0 24px">A new invoice has been generated by <strong>${firm?.name || 'your firm'}</strong>.</p>
                <div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:12px;padding:24px;margin:0 0 24px">
                  <div style="margin-bottom:12px">
                    <p style="font-size:12px;color:#64748B;margin:0 0 4px">Invoice number</p>
                    <p style="font-size:16px;font-weight:700;color:#0F172A;margin:0">${invoiceNumber}</p>
                  </div>
                  <div style="margin-bottom:12px">
                    <p style="font-size:12px;color:#64748B;margin:0 0 4px">Description</p>
                    <p style="font-size:14px;color:#0F172A;margin:0">${rec.description || 'Services'}</p>
                  </div>
                  <div style="margin-bottom:12px">
                    <p style="font-size:12px;color:#64748B;margin:0 0 4px">Amount due</p>
                    <p style="font-size:28px;font-weight:900;color:#1C64F2;margin:0">${cur.symbol}${rec.amount.toLocaleString()}</p>
                  </div>
                  <div>
                    <p style="font-size:12px;color:#64748B;margin:0 0 4px">Due date</p>
                    <p style="font-size:14px;font-weight:600;color:#DC2626;margin:0">${new Date(dueDate).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</p>
                  </div>
                </div>
                <div style="text-align:center;margin:28px 0">
                  <a href="${portalUrl}" style="display:inline-block;background:#1C64F2;color:#fff;padding:14px 36px;border-radius:10px;text-decoration:none;font-weight:700;font-size:15px">View in portal →</a>
                </div>
              </div>
              <p style="text-align:center;color:#94A3B8;font-size:12px;margin-top:20px">Powered by <strong>FirmFlow</strong> · firmflow.uk</p>
            </div>
          `
        })
      } catch (e) {
        console.error('Email error:', e)
      }
    }

    generated++
  }

  return NextResponse.json({ success: true, generated })
}