import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://firmflow.io'
  const now = new Date()

  return [
    { url: baseUrl, lastModified: now, changeFrequency: 'weekly', priority: 1.0 },
    { url: baseUrl + '/signup', lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: baseUrl + '/blog', lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: baseUrl + '/blog/firmflow-vs-competitors', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: baseUrl + '/blog/best-practice-management-software-2026', lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: baseUrl + '/blog/docusign-alternative-for-firms', lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: baseUrl + '/blog/client-portal-for-accountants', lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: baseUrl + '/blog/replace-five-tools-with-one', lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: baseUrl + '/blog/legally-binding-e-signatures-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: baseUrl + '/blog/save-money-practice-management', lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
        { url: baseUrl + '/taxdome-alternative', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: baseUrl + '/vs-taxdome', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: baseUrl + '/vs-karbon', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: baseUrl + '/vs-clio', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
    { url: baseUrl + '/demo', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/why-firmflow', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/karbon-alternative', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/for-accountants', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.9 },
        { url: baseUrl + '/for-lawyers', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.9 },
        { url: baseUrl + '/changelog', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.5 },
        { url: baseUrl + '/for-consultants', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.9 },
        { url: baseUrl + '/blog/how-to-choose-practice-management-software', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/blog/are-electronic-signatures-legally-binding', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/clio-alternative', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/pricing', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.9 },
        { url: baseUrl + '/security', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
        { url: baseUrl + '/switch', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/blog/outgrown-spreadsheets', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
        { url: baseUrl + '/docusign-alternative', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/for-bookkeepers', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.9 },
        { url: baseUrl + '/sitemap-page', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.3 },
        { url: baseUrl + '/sharefile-alternative', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/about', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.6 },
        { url: baseUrl + '/blog/what-is-a-client-portal', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
        { url: baseUrl + '/tools', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
        { url: baseUrl + '/tools/invoice-template', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
        { url: baseUrl + '/tools/engagement-letter', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/help', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.6 },
        { url: baseUrl + '/calculator', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.8 },
        { url: baseUrl + '/nl/accountants', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.9 },
    { url: baseUrl + '/de/accountants', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.9 },
    { url: baseUrl + '/contact', lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: baseUrl + '/login', lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: baseUrl + '/privacy', lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    { url: baseUrl + '/terms', lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
      { url: baseUrl + '/resources', lastModified: now, changeFrequency: 'weekly' as const, priority: 0.8 },
    { url: baseUrl + '/tools/hourly-rate-calculator', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/tools/quote-generator', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/tools/vat-calculator', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/guides/practice-management-software', lastModified: now, changeFrequency: 'weekly' as const, priority: 0.95 },
    { url: baseUrl + '/blog/practice-management-software-for-sole-practitioners', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/blog/how-to-switch-from-taxdome', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/blog/gdpr-compliant-client-portal-for-accountants', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/press', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.6 },
    { url: baseUrl + '/blog/engagement-letter-template-accountants-uk', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/blog/multi-currency-invoicing-small-firms', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/blog/docusign-vs-firmflow', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/integrations', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/karbon-vs-taxdome', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/clio-vs-karbon', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/for-tax-advisors', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/for-coaches', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/for-architects', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/blog/bookkeeping-software-small-uk-businesses', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/blog/practice-management-solo-lawyers', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: baseUrl + '/blog/time-tracking-accountants-comparison', lastModified: now, changeFrequency: 'monthly' as const, priority: 0.7 },
]
}
